# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spigot Build

on:
  schedule:
    - cron: '0 10 1-30/3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable
      run: |
        echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV
        test $(date +%d) = 01 -o $(date +%d) = 16 && echo "buildLegacy=true" >> $GITHUB_ENV || echo "buildLegacy=false" >> $GITHUB_ENV
    - uses: actions/checkout@v4
      with:
        path: buildtool
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Get YAML python package
      run: pip install pyyaml
    - name: Set up BuildTool
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
        mkdir -p output
      working-directory: buildtool
    - name: Cache .m2 folder
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-cache-maven-${{ env.date }}
        restore-keys: ${{ runner.os }}-cache-maven-
    - name: Cache Spigot repos
      uses: actions/cache@v4
      with:
        path: |
          buildtool/apache-maven-*
          buildtool/Bukkit
          buildtool/CraftBukkit
          buildtool/Spigot
        key: ${{ runner.os }}-cache-spigot-${{ env.date }}
        restore-keys: ${{ runner.os }}-cache-spigot-
    - name: Cache build works
      uses: actions/cache@v4
      with:
        path: buildtool/work
        key: ${{ runner.os }}-cache-build-work-${{ env.date }}
        restore-keys: ${{ runner.os }}-cache-build-work-
    - name: Build new version Spigot
      run: python3 build.py new
      working-directory: buildtool
    - name: Set up JDK 17
      if: ${{ fromJSON(env.buildLegacy) || github.event_name == 'workflow_dispatch' }}
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build legacy version Spigot with Java 17
      if: ${{ fromJSON(env.buildLegacy) || github.event_name == 'workflow_dispatch' }}
      run: python3 build.py legacy-java-17
      working-directory: buildtool
    - name: Set up JDK 8
      if: ${{ fromJSON(env.buildLegacy) || github.event_name == 'workflow_dispatch' }}
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build legacy version Spigot with Java 8
      if: ${{ fromJSON(env.buildLegacy) || github.event_name == 'workflow_dispatch' }}
      run: python3 build.py legacy-java-8
      working-directory: buildtool
    - name: Download previous build
      uses: robinraju/release-downloader@v1.10
      if: ${{ fromJSON(env.buildLegacy) != true }}
      with:
        latest: true
        fileName: "*.jar"
        out-file-path: "release"
    - name: Copy build output
      run: mkdir -p release && mv buildtool/output/*.jar release/
    - name: Generate readme
      run: python3 ../buildtool/table.py ${{ env.date }} README.md
      working-directory: release
    - name: Push builds to release branch
      run: |
        git init
        git config user.name "github-actions"
        git config user.email "41898282+github-actions@users.noreply.github.com"
        git remote add origin "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}"
        git checkout -b release
        git add README.md
        git commit -m "${{ env.date }} Build"
        git push -f origin release
      working-directory: release
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.date }} Build
        tag_name: ${{ env.date }}
        target_commitish: release
        files: release/*.jar
        body_path: release/README.md
